'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ItmSel

    '''<summary>
    '''frmItmSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmItmSel As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hfShowStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfShowStock As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlK1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblK1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnK1Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnK1Select As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdK1 As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlK2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblK2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnK2Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnK2Select As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdK2 As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlK3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblK3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnK3Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnK3Select As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdK3 As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlK4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblK4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnK4Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnK4Select As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdK4 As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ibtnRestart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRestart As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnGet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGet As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCheck As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdItm As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lbtnItmFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnItmFirst As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnItmPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnItmPrev As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnItmNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnItmNext As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnItmLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnItmLast As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblItmPCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItmPCnt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inpPageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inpPageType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''pnlBtnOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnOrd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblQtyOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtyOrd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtyOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyOrd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnAddOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAddOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnKitOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnKitOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnCartOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCartOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlBtnItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnItm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ibtnBackItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnBackItm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnEditItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEditItm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlBtnKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnKit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtQtyKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyKit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQtyKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtyKit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnAddKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAddKit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnBackKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnBackKit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vMaxQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMaxQty As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''txtSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmit As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmRow As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmSelCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmSelCnt As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmsSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmsSelected As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmSelFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmSelFrom As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosK1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosK2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosK3 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosK4 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosItm As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollYPosItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollYPosItm As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosDoc As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollYPosDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollYPosDoc As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LoadTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadTime As Global.System.Web.UI.WebControls.Literal
End Class
