'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ItmVw

    '''<summary>
    '''frmItmVw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmItmVw As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlItm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblImgRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImgRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblImgDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImgDes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgItem As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblExtendedDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtendedDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lkHigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkHigh As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblHighSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHighSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lkBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkBase As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblBaseSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBaseSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lkLow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkLow As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblLowSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLowSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDownload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptDownloadables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDownloadables As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlNoItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoItm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNoItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoItm As Global.System.Web.UI.WebControls.Label
End Class
