'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KitSel

    '''<summary>
    '''frmKitSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmKitSel As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hfShowStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfShowStock As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlK1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblK1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnK1Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnK1Select As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdK1 As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ibtnRestart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRestart As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnGet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnGet As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCheck As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdItm As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ibtnViewKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnViewKit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnEditKit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEditKit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblKitRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKitRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKitDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKitDes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKitNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKitNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlBtnOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnOrd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblQtyOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtyOrd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtyOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyOrd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnAddOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAddOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnItmOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnItmOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnCartOrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCartOrd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vMaxQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMaxQty As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''txtSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmit As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmRow As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmSelCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmSelCnt As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtItmSelFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItmSelFrom As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosK1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosItm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosItm As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollXPosDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollXPosDoc As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScrollYPosDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollYPosDoc As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
